---
title: "marcos_perazo_viana_analise_exploratoria_de_dados_pd"
author: "Marcos Perazo Viana"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
tinytex::install_tinytex(force = TRUE)
```

## Carregando bibliotecas

```{r importando bibliotecas 1, echo = TRUE}
library(tidyverse)
library(tidyr)
library(purrr)
library(dlookr)
library(summarytools)
library(readxl)
library(knitr)
library(data.table)
library(ggpubr)
library(corrplot)
```

## Introdução - Bibliotecas (parte 2)

```{r importando bibliotecas 2, echo = TRUE}
library(rcompanion)
library(stargazer)
library(mice)
library(rmarkdown)
library(tinytex)
library(sandwich)
library(magrittr)
library(shiny)
library(plm)
```

### 4 - Carregamento da base.

```{r Carregamento da base de jogadores da NBA, echo=TRUE}
dados_tratados <- read_csv("Dados_auxiliares/dados_apos_coluna_mes.csv", quote = "\"", locale = locale(encoding = "UTF-8"))
```

```{r Tratamento dados númericos, echo=TRUE}
dados <- dados_tratados %>%
  mutate(
    PPG = as.numeric(PPG),
    RPG = as.numeric(RPG),
    APG = as.numeric(APG),
  )
```

```{r frota, echo=TRUE}
kable(head(dados))
```

